# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job:
    name: ${{ matrix.os }}-build-and-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            openmp: ON
            builddir: dist/wheelhouse
            builddir1: dist
          - os: ubuntu-latest
            triplet: x64-linux
            builddir: wheelhouse
            builddir1: wheelhouse
          - os: macos-latest
            triplet: x64-osx
            builddir: wheelhouse
            builddir1: wheelhouse
    env:
      # Indicates the CMake build directory where project files and binaries are being produced.
      CMAKE_BUILD_DIR: ${{ github.workspace }}/builddir/
      # Indicates the location of the vcpkg as a Git submodule of the project repository.
      VCPKG_ROOT: ${{ github.workspace }}/external/LibAPR/vcpkg
      CIBW_ENVIRONMENT_WINDOWS: EXTRA_CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=D:\\a\\PyLibAPR\\PyLibAPR\\external\\LibAPR\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake -DVCPKG_MANIFEST_DIR=D:\\a\\PyLibAPR\\PyLibAPR\\external\\LibAPR\\"
#      CIBW_ENVIRONMENT_LINUX: EXTRA_CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=/home/runner/work/PyLibAPR/PyLibAPR/external/LibAPR/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_MANIFEST_DIR=/home/runner/work/PyLibAPR/PyLibAPR/external/LibAPR/"
#      CIBW_ENVIRONMENT_MACOS: EXTRA_CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=/Users/runner/work/PyLibAPR/PyLibAPR/external/LibAPR/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_MANIFEST_DIR=/Users/runner/work/PyLibAPR/PyLibAPR/external/LibAPR/"
#      EXTRA_CMAKE_ARGS: -DCMAKE_TOOLCHAIN_FILE=D:\\a\\PyLibAPR\\PyLibAPR\\external\\LibAPR\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake -DVCPKG_MANIFEST_DIR=D:\\a\\PyLibAPR\\PyLibAPR\\external\\LibAPR\\
#      TEST: EXTRA_CMAKE_ARGS="-DCMAKE_TOOLCHAIN_FILE=D:\\a\\PyLibAPR\\PyLibAPR\\external\\LibAPR\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake -DVCPKG_MANIFEST_DIR=D:\\a\\PyLibAPR\\PyLibAPR\\external\\LibAPR\\"
#      CIBW_BUILD: "cp36-* cp37-* cp38-* cp39-*"
      CIBW_BUILD: "cp36-*"
      CIBW_ARCHS: "auto64"
      CIBW_MANYLINUX_X86_64_IMAGE: "manylinux_2_24"
      TWINE_USERNAME: __token__
      CIBW_BUILD_VERBOSITY: 3
      CIBW_REPAIR_WHEEL_COMMAND_MACOS: "pip uninstall -y delocate && pip install git+https://github.com/Chia-Network/delocate.git && delocate-listdeps {wheel} && delocate-wheel -w {dest_dir} -v {wheel}"
      CIBW_BEFORE_TEST: "pip install -r requirements.txt"
      CIBW_TEST_COMMAND: "python3 -m unittest"
      CIBW_BEFORE_BUILD_LINUX: "apt update && apt install -y libtiff5-dev libhdf5-dev"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Submodule recursive
        run: git submodule update --init --recursive

      # Setup the build machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
      - uses: lukka/get-cmake@latest
      # Restore both vcpkg and its artifacts from the GitHub cache service.
      - name: Restore vcpkg and its artifacts.
        uses: actions/cache@v2
        with:
          # The first path is where vcpkg generates artifacts while consuming the vcpkg.json manifest file.
          # The second path is the location of vcpkg (it contains the vcpkg executable and data files).
          # The other paths starting with '!' are exclusions: they contain termporary files generated during the build of the installed packages.
          path: |
            ${{ env.CMAKE_BUILD_DIR }}/vcpkg_installed/
            ${{ env.VCPKG_ROOT }}
            !${{ env.VCPKG_ROOT }}/buildtrees
            !${{ env.VCPKG_ROOT }}/packages
            !${{ env.VCPKG_ROOT }}/downloads
          # The key is composed in a way that it gets properly invalidated: this must happen whenever vcpkg's Git commit id changes, or the list of packages changes. In this case a cache miss must happen and a new entry with a new key with be pushed to GitHub the cache service.
          # The key includes: hash of the vcpkg.json file, the hash of the vcpkg Git commit id, and the used vcpkg's triplet. The vcpkg's commit id would suffice, but computing an hash out it does not harm.
          # Note: given a key, the cache content is immutable. If a cache entry has been created improperly, in order the recreate the right content the key must be changed as well, and it must be brand new (i.e. not existing already).
          key: |
            ${{ hashFiles( 'external/LibAPR/vcpkg.json' ) }}-${{ hashFiles( '.git/modules/vcpkg/HEAD' )}}-${{ matrix.triplet }}-invalidate

      - name: check file paths
        run: |
          cd ${{ github.workspace }}/external/LibAPR/vcpkg/scripts/buildsystems/
          ls

      - name: Show content of workspace after cache has been restored
        run: find $RUNNER_WORKSPACE
        shell: bash

      # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly. As used here the Developer Command Prompt created is targeting x64 and using the default the Windows SDK.
      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.10.0

      - name: Install OpenMP dependencies with brew for OSX
        if: contains(matrix.os,'macos')
        run: |
          brew install libomp
          brew install c-blosc
          brew install hdf5
#
      - name: Run cibuildwheel
        run: |
          python3 -m cibuildwheel --output-dir ${{matrix.builddir1}}
#
#      - name: Install dependencies and generate project files
#        run: |
#          cmake -S "${{ github.workspace }}" -B "${{ env.CMAKE_BUILD_DIR }}" ${{ env.TEST}}
      - name: Fix windows wheels
        if: contains(matrix.os,'windows')
        run: |
          python3 -m pip install wheel
          python3 -m pip install delvewheel
          python3 fix_windows_wheel.py

      - name: Install twine
        run: |
          python3 -m pip install twine

      - name: Publish to test Pypi
        run: |
          python3 -m twine upload --skip-existing --repository testpypi ${{matrix.builddir}}/*.whl -p ${{ secrets.TEST_PYPI_API_TOKEN }}
